name: sora_gov_agree
description: Mobile app for SORA Gov-Agree
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.21.0
  provider: ^3.1.0
  equatable: ^0.6.1
  cupertino_icons: ^0.1.2
  intro_slider:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
